services:
  # Servicio para tu aplicación Spring Boot
  mi-spring-app:
    image: 'tomcat:latest'
    build:
      context: . #'https://github.com/miuguelt/Git-Spring.git'
      dockerfile: Dockerfile
    container_name: mi-springboot-container
    restart: unless-stopped
    ports:
      - "8090:8080"

volumes:
  mongodb_data: {} # Define el volumen para los datos de MongoDB
